# Generated by Django 4.2 on 2024-01-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdealData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('sleeping_hours', models.FloatField()),
                ('bmi', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.FloatField()),
                ('activity_level', models.CharField(choices=[('Light', 'Light Activity'), ('Moderate', 'Moderate Activity'), ('Heavy', 'Heavy Activity')], max_length=20)),
                ('sleeping_hours', models.FloatField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
